### ISSUE TITLE
Question: API SLA uptime?

### ISSUE THREAD

**Issue by leafypout** [volsa/etherface#3]
I noticed the API is being hosted on Hetzner and I wanted to ask if this is being hosted on a single instance or if it's being load balanced. I'm also curious if there's any guaranteed SLA uptime, and if you've tested how many requests/second the API can handle.

**Comment by volsa** [comment]
> I noticed the API is being hosted on Hetzner and I wanted to ask if this is being hosted on a single instance or if it's being load balanced.

Except for the UI, everything is currently hosted on a single instance. There are no plans to change the architecture to a distributed one, simply because I want to keep the architecture simple and costs low. Load balancing isn't planned either, which I would replace with IP based API ratelimiting anyways.

> I'm also curious if there's any guaranteed SLA uptime

No guarantees, as it is a side project after all. That being said you can assume that the REST API will be running 24/7, except every 3 months or so when I have to renew the LetsEncrypt certificate. Renewal should take anywhere between hours and at most 1-2 days.

> if you've tested how many requests/second the API can handle.

Nope, but the `/v1/signatures/hash` endpoint which is used the most handles request within 100ms on average according to the API logs. Combining this with mutli-threading I'm assuming it can handle quite a few requests per second.

**Comment by volsa** [comment]
As a side note: REST API specific database access can always be replaced with async code, scaling it even further than what would be possible with threads. Hope that clears things up for you.
